### ISSUE TITLE
Invalidations fail although the number of invalidations decreases

### ISSUE THREAD

**Issue by ranocha** [julia-actions/julia-invalidations#8] opened 2022-12-15 10:03 UTC
I get the following report in https://github.com/trixi-framework/P4est.jl/pull/49

```
Run echo "Invalidations on default branch: 1748 (1748 via deps)" >> $GITHUB_STEP_SUMMARY
  echo "Invalidations on default branch: 1748 (1748 via deps)" >> $GITHUB_STEP_SUMMARY
  echo "This branch: 270 (270 via deps)" >> $GITHUB_STEP_SUMMARY
  shell: /usr/bin/bash -e {0}

Error: Process completed with exit code 1.
```

See https://github.com/trixi-framework/P4est.jl/actions/runs/3702860172/jobs/6273612069

**Comment by ChrisRackauckas** [comment] 2023-01-11 15:13
I've seen this as well. Any way to make it a regression test, not just a test if invalidations are pure zero?

**Comment by KristofferC** [comment] 2024-07-12 13:18
https://github.com/julia-actions/julia-invalidations/issues/16#issuecomment-2225561641 is the reason for this

**Comment by IanButterworth** [comment] 2024-11-24 15:24
Fixed by https://github.com/julia-actions/julia-invalidations/pull/35

**Closed by IanButterworth** 2024-11-24 15:24 UTC
